name: Dependabot auto-merge
on:
  check_suite:
    types: [completed]

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.check_suite.conclusion == 'success' &&
        github.event.check_suite.pull_requests[0].user.login == 'dependabot[bot]'
      }}
    steps:
      - name: Auto-merge Dependabot PR
        env:
          PR_URL: ${{ github.event.check_suite.pull_requests[0].html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BASE_BRANCH: ${{ github.event.check_suite.pull_requests[0].base.ref }}
        run: |
          set -euo pipefail
          echo "Checking branch protection rules for ${BASE_BRANCH}..."

          # Make a single API call to get branch protection info
          branch_protection_json=$(gh api repos/${REPO}/branches/${BASE_BRANCH}/protection --silent 2>/dev/null || echo '{}')

          # Check if required_status_checks is present (not null)
          if ! echo "$branch_protection_json" | jq -e '.required_status_checks != null' > /dev/null; then
            echo "::error::Branch protection for ${BASE_BRANCH} does not require status checks. Exiting."
            exit 1
          fi

          echo "✅ Branch protection with required status checks is properly configured."

          echo "Enabling auto-merge for PR: ${PR_URL}..."
          gh pr merge --auto --rebase "${PR_URL}"
          echo "Auto-merge enabled. The PR will merge automatically once all required checks pass."
