name: Gemini tests

on: pull_request_target

jobs:
  test-gemini:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache test model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: /Users/runner/.humanifyjs/models/
          key: models-phi
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install --ci
      - run: npm run build
      - run: npm run download-ci-model
      - run: npm run test:gemini
        env:
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
